module.exports = {
	"sendSMS": "sms/send",
	"checkStatus": "sms/status",
	"sendedList": "sms/list",
	"balance": "balance",
	"tariffs": "tariffs",
	"addSign": "sign/add",
	"signList": "sign/list",
	"addGroup": "group/add",
	"deleteGroup": "group/delete",
	"groupList": "group/list",
	"addContact": "contact/add",
	"deleteContact": "contact/delete",
	"contactList": "contact/list",
	"addBlacklist": "blacklist/add",
	"deleteBlacklist": "blacklist/delete",
	"blacklistList": "blacklist/list",
	"hlrCheck": "hlr/check",
	"hlrStatus": "hlr/status",
	"checkOperator": "number/operator",
	"sendViber": "viber/send",
	"checkViberStat": "viber/statistic",
	"viberList": "viber/list",
	"viberSignList": "viber/sign/list"
};